### PR TITLE
Update AzureDevOpsTls12Analysis.ps1

### PR DESCRIPTION
**Pull request by AlanFlorance**
Updated $null tests and switch docs to learn links

### CODE REVIEW

**Comment by AlanFlorance** [comment]
@microsoft-github-policy-service agree

**Comment by AlanFlorance** [comment]
Updated $null tests and switch docs to learn links

**Comment by AlanFlorance** [comment]
Updated $null tests and switch docs to learn links

**Comment by on-the-ray** [comment]
Sorry for late review. Good changes, thank you!

**Pull request merged**
